import type { IStaticLandingPlan } from '@/types/plan.type';

/** Static pricing shown on clusterboard.pl — update here when plans change. */
export const STATIC_LANDING_PLANS: IStaticLandingPlan[] = [
  {
    plan_key: 'free',
    price_amount: 0,
    currency: 'PLN',
    billing_type: 'free',
    is_active: true,
    landing_featured: false,
    landing_title: 'Free',
    landing_subtitle: 'Start i pierwsze projekty',
    landing_features: [
      '1 aktywny projekt',
      'Do 5 inspiracji / projekt',
      'Do 3 dokumentów / projekt',
      '1 inwestor na projekt',
      'Wiadomości bez limitu',
    ],
    landing_price_period: '/ miesiąc',
    landing_badge: null,
    landing_savings: null,
    landing_cta: 'Załóż darmowe konto',
  },
  {
    plan_key: 'one_time',
    price_amount: 29.99,
    currency: 'PLN',
    billing_type: 'one_time',
    is_active: false,
    landing_featured: false,
    landing_title: 'Pojedyncza Tablica',
    landing_subtitle: 'Freelancerzy i małe zlecenia',
    landing_features: [
      '1 aktywny projekt',
      'Do 8 inspiracji / projekt',
      'Do 3 dokumentów / projekt',
      'Max 2 inwestorów',
    ],
    landing_price_period: '/ miesiąc',
    landing_badge: null,
    landing_savings: null,
    landing_cta: 'Rozpocznij',
  },
  {
    plan_key: 'basic',
    price_amount: 49.99,
    currency: 'PLN',
    billing_type: 'monthly',
    is_active: false,
    landing_featured: true,
    landing_title: 'Plan Miesięczny (Basic)',
    landing_subtitle: 'Aktywne ekipy i dekoratorzy',
    landing_features: [
      '3 aktywne projekty',
      'Do 20 inspiracji / projekt',
      'Do 10 dokumentów / projekt',
      '2 inwestorów',
    ],
    landing_price_period: '/ miesiąc',
    landing_badge: 'NAJPOPULARNIEJSZY',
    landing_savings: null,
    landing_cta: 'Rozpocznij',
  },
  {
    plan_key: 'pro',
    price_amount: 89.99,
    currency: 'PLN',
    billing_type: 'monthly',
    is_active: false,
    landing_featured: false,
    landing_title: 'Plan Miesięczny (Pro)',
    landing_subtitle: 'Firmy z portfelem zleceń',
    landing_features: [
      'Nielimitowane projekty',
      'Do 50 inspiracji / projekt',
      'Do 20 dokumentów / projekt',
      'Nielimitowani inwestorzy',
    ],
    landing_price_period: '/ miesiąc',
    landing_badge: null,
    landing_savings: 'Oszczędzasz N/A PLN rocznie',
    landing_cta: 'Rozpocznij',
  },
];
